# Message
message:
  source:
    basename: i18n/messages

# Card
card:
  cipher:
    type: DESede
    key: kakaopaykakaopaykakaopay
    separator: |

# Spring
spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    database: h2
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      use-new-id-generator-mappings: true
  datasource:
    sql-script-encoding: UTF-8
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
  http:
    encoding:
      charset: utf-8
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console